#!/bin/bash

project_root=${project_root:-..}
bash_build_scripts=$project_root/support/lib/bash_build_scripts
lib="$bash_build_scripts/build_lib"
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

#prepare
section "running make"
cd $build_root || ferr "failed to change into build dir"
#command
if [[ $generator == "ninja" ]]; then
    ninja
else
    make -j $(nproc) || ferr "running make - failed" $?
fi
#end
echo
