#!/bin/bash

project_root=${project_root:-..}
bash_build_scripts=$project_root/support/lib/bash_build_scripts
lib="$bash_build_scripts/build_lib"
if [[ -f "$lib" ]]; then
    . "$lib"
else
    echo "${build_prefix}unable to source build_lib"
    exit 1
fi

#prepare
section "system info"
#command
echo "sources list ##################"
cat /etc/apt/sources.list
echo "cpu info ######################"
cat /proc/cpuinfo
echo "mem info ######################"
cat /proc/meminfo
echo "###############################"
#end
echo
