#!/usr/bin/env python3
# Copyright - 2019 - Jan Christoph Uhde <Jan@UhdeJC.com>

import sys
import os
import logging
from pathlib import Path


if sys.version_info[0] < 3 or sys.version_info[1] < 7:
    raise Exception("Must be using Python 3.7")

# add local modules path
project_dir = Path(os.getcwd())
support_dir = Path(__file__).parent.parent.resolve()
modules_dir = support_dir.joinpath("lib", "python_modules")
sys.path.insert(0, str(modules_dir))

from codecheck import Status, Configuration, logger, check_modify_source   # noqa: E402

if __name__ == "__main__":
    if "--debug" in sys.argv:
        logger.setLevel(logging.DEBUG)

    # parameters
    modify = True
    dirs = ["include", "examples", "tests"]  # dirs to include
    dirs_to_exclude = []

    # run
    ctx = Configuration(project_dir, modify, dirs, dirs_to_exclude)
    status = check_modify_source(ctx)
    sys.exit(int(status))
